In [1]:
import sys

print(sys.version)

3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]

In [2]:
import sys

print(sys.version)

3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

ModuleNotFoundError: No module named 'pandas'

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

ModuleNotFoundError: No module named 'pandas'

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [6]:
df = pd.read_csv("../data/student_performance.csv")

In [7]:
print(df.head())
print(df.shape)
print(df.columns)

   Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9
1              4               82                         No            4
2              8               51                        Yes            7
3              5               52                        Yes            5
4              7               75                         No            8

   Sample Question Papers Practiced  Performance Index
0                                 1               91.0
1                                 2               65.0
2                                 2               45.0
3                                 2               36.0
4                                 5               66.0
(10000, 6)
Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='str')

In [8]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [9]:
print(df.shape)

(10000, 6)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  str
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), str(1)
memory usage: 468.9 KB

In [11]:
print(df.dtypes)

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities              str
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [12]:
print(df.isnull().sum())

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [13]:
X = df.drop(columns=["Class"])
y = df["Class"]

KeyError: "['Class'] not found in axis"

In [14]:
print("X:", X.shape)
print("y:", y.shape)

NameError: name 'X' is not defined

In [15]:
print("X:", X.shape)
print("y:", y.shape)

NameError: name 'X' is not defined

In [16]:
X = df.drop(columns=["Class"])
y = df["Class"]

KeyError: "['Class'] not found in axis"

In [17]:
X = df.drop(columns=["Performance Index"])
y = df["Performance Index"]

print("X:", X.shape)
print("y:", y.shape)

X: (10000, 5)
y: (10000,)

In [18]:
numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category", "str"]
).columns.tolist()

print("Числовые признаки:")
print(numeric_features)

print("\nКатегориальные признаки:")
print(categorical_features)

Числовые признаки:
['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']

Категориальные признаки:
['Extracurricular Activities']

In [19]:
numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category", "str"]
).columns.tolist()

print("Числовые признаки:")
print(numeric_features)

print("\nКатегориальные признаки:")
print(categorical_features)

Числовые признаки:
['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']

Категориальные признаки:
['Extracurricular Activities']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (8000, 5)
X_test: (2000, 5)
y_train: (8000,)
y_test: (2000,)

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

In [22]:
from sklearn.preprocessing import OneHotEncoder

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(
            strategy="constant",
            fill_value="missing"
        )),
        ("onehot", OneHotEncoder(
            handle_unknown="ignore"
        ))
    ]
)

In [23]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [24]:
X_train_transformed = preprocessor.fit_transform(X_train)

In [25]:
X_test_transformed = preprocessor.transform(X_test)

In [26]:
preprocessor.fit_transform(X_train)

array([[ 0.00645547, -1.18384439,  0.26988848,  0.13404112,  1.        ,
         0.        ],
       [-1.14974745, -1.24150571,  0.26988848,  0.48356164,  0.        ,
         1.        ],
       [-1.14974745,  0.66131759,  0.26988848, -0.91452044,  1.        ,
         0.        ],
       ...,
       [ 1.54805935, -1.24150571,  0.26988848,  0.48356164,  1.        ,
         0.        ],
       [-1.53514842, -1.29916702,  1.4474766 , -1.61356148,  1.        ,
         0.        ],
       [-1.14974745, -1.35682833, -0.31890558,  0.48356164,  1.        ,
         0.        ]], shape=(8000, 6))

In [27]:
preprocessor.transform(X_test)

array([[ 0.00645547, -0.03061816,  0.85868254, -0.91452044,  1.        ,
         0.        ],
       [-1.14974745, -1.35682833, -1.49649371,  1.18260268,  0.        ,
         1.        ],
       [ 0.77725741, -0.78021521,  0.26988848,  0.13404112,  0.        ,
         1.        ],
       ...,
       [-1.14974745, -1.7027962 ,  0.26988848, -0.91452044,  0.        ,
         1.        ],
       [-0.76434648,  0.77664021,  0.26988848,  0.13404112,  1.        ,
         0.        ],
       [ 0.00645547, -0.54956996,  0.85868254, -0.2154794 ,  1.        ,
         0.        ]], shape=(2000, 6))

In [28]:
print("Исходные размеры:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nПосле preprocessing:")
print("X_train_transformed:", X_train_transformed.shape)
print("X_test_transformed:", X_test_transformed.shape)

Исходные размеры:
X_train: (8000, 5)
X_test: (2000, 5)

После preprocessing:
X_train_transformed: (8000, 6)
X_test_transformed: (2000, 6)

In [29]:
feature_names = preprocessor.get_feature_names_out()

print("Итоговые признаки:")
for name in feature_names:
    print(name)

Итоговые признаки:
num__Hours Studied
num__Previous Scores
num__Sleep Hours
num__Sample Question Papers Practiced
cat__Extracurricular Activities_No
cat__Extracurricular Activities_Yes

In [30]:
print("Количество пропусков:")
print(df.isnull().sum())

print("\nВсего пропусков:")
print(df.isnull().sum().sum())

Количество пропусков:
Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

Всего пропусков:
0

In [31]:
print("Preprocessor обучен на:")
print("X_train")

print("\nTrain shape:")
print(X_train_transformed.shape)

print("\nTest shape:")
print(X_test_transformed.shape)

Preprocessor обучен на:
X_train

Train shape:
(8000, 6)

Test shape:
(2000, 6)

In [32]:
preprocessor.fit_transform(X_train)

array([[ 0.00645547, -1.18384439,  0.26988848,  0.13404112,  1.        ,
         0.        ],
       [-1.14974745, -1.24150571,  0.26988848,  0.48356164,  0.        ,
         1.        ],
       [-1.14974745,  0.66131759,  0.26988848, -0.91452044,  1.        ,
         0.        ],
       ...,
       [ 1.54805935, -1.24150571,  0.26988848,  0.48356164,  1.        ,
         0.        ],
       [-1.53514842, -1.29916702,  1.4474766 , -1.61356148,  1.        ,
         0.        ],
       [-1.14974745, -1.35682833, -0.31890558,  0.48356164,  1.        ,
         0.        ]], shape=(8000, 6))

In [33]:
preprocessor.transform(X_test)

array([[ 0.00645547, -0.03061816,  0.85868254, -0.91452044,  1.        ,
         0.        ],
       [-1.14974745, -1.35682833, -1.49649371,  1.18260268,  0.        ,
         1.        ],
       [ 0.77725741, -0.78021521,  0.26988848,  0.13404112,  0.        ,
         1.        ],
       ...,
       [-1.14974745, -1.7027962 ,  0.26988848, -0.91452044,  0.        ,
         1.        ],
       [-0.76434648,  0.77664021,  0.26988848,  0.13404112,  1.        ,
         0.        ],
       [ 0.00645547, -0.54956996,  0.85868254, -0.2154794 ,  1.        ,
         0.        ]], shape=(2000, 6))

In [34]:
print("=== DATASET ===")
print("Размер исходных данных:", df.shape)

print("\n=== FEATURES ===")
print("Числовые:", numeric_features)
print("Категориальные:", categorical_features)

print("\n=== TRAIN / TEST ===")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\n=== AFTER PREPROCESSING ===")
print("X_train_transformed:", X_train_transformed.shape)
print("X_test_transformed:", X_test_transformed.shape)

print("\n=== FINAL FEATURES ===")
print(preprocessor.get_feature_names_out())

=== DATASET ===
Размер исходных данных: (10000, 6)

=== FEATURES ===
Числовые: ['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']
Категориальные: ['Extracurricular Activities']

=== TRAIN / TEST ===
X_train: (8000, 5)
X_test: (2000, 5)

=== AFTER PREPROCESSING ===
X_train_transformed: (8000, 6)
X_test_transformed: (2000, 6)

=== FINAL FEATURES ===
['num__Hours Studied' 'num__Previous Scores' 'num__Sleep Hours'
 'num__Sample Question Papers Practiced'
 'cat__Extracurricular Activities_No'
 'cat__Extracurricular Activities_Yes']

In [35]:
import pandas as pd

transformed_df = pd.DataFrame(
    X_train_transformed,
    columns=preprocessor.get_feature_names_out()
)

transformed_df.head()

,num__Hours Studied,num__Previous Scores,num__Sleep Hours,num__Sample Question Papers Practiced,cat__Extracurricular Activities_No,cat__Extracurricular Activities_Yes
0,0.006455,-1.183844,0.269888,0.134041,1.0,0.0
1,-1.149747,-1.241506,0.269888,0.483562,0.0,1.0
2,-1.149747,0.661318,0.269888,-0.914520,1.0,0.0
3,-1.149747,-1.356828,-0.318906,-1.264041,1.0,0.0
4,1.162658,-1.299167,1.447477,-1.613561,1.0,0.0

In [36]:
transformed_df.describe()

,num__Hours Studied,num__Previous Scores,num__Sleep Hours,num__Sample Question Papers Practiced,cat__Extracurricular Activities_No,cat__Extracurricular Activities_Yes
count,8.000000e+03,8.000000e+03,8.000000e+03,8.000000e+03,8000.000000,8000.000000
mean,2.842171e-17,-3.321787e-16,1.367795e-16,-8.171241e-17,0.505375,0.494625
std,1.000063e+00,1.000063e+00,1.000063e+00,1.000063e+00,0.500002,0.500002
min,-1.535148e+00,-1.702796e+00,-1.496494e+00,-1.613561e+00,0.000000,0.000000
25%,-7.643465e-01,-8.522919e-01,-9.076996e-01,-9.145204e-01,0.000000,0.000000
50%,6.455466e-03,2.704316e-02,2.698885e-01,1.340411e-01,1.000000,0.000000
75%,7.772574e-01,8.919628e-01,8.586825e-01,8.330822e-01,1.000000,1.000000
max,1.548059e+00,1.699221e+00,1.447477e+00,1.532123e+00,1.000000,1.000000

In [37]:
y = df["Performance Index"]

### Conclusion

The dataset contains 10,000 observations and 6 columns. The target variable is `Performance Index`. Four input features are numerical and one feature, `Extracurricular Activities`, is categorical.

The numerical features are processed using median imputation and `StandardScaler`. The categorical feature is processed using a separate `"missing"` category and `OneHotEncoder`.

The preprocessing is fitted only on the training data and then applied to the test data. Therefore, information from the test set is not used during preprocessing, which prevents data leakage.

The original feature space contains 5 input features. After preprocessing, the number of features becomes 6 because the categorical feature is transformed into two one-hot encoded features.

The final dimensions are 8000 × 6 for the training data and 2000 × 6 for the test data.